### ISSUE TITLE
[FEAT-REQ]: count of checked items in a parent node

### ISSUE THREAD

**Issue by OmkarK45** [JairajJangle/react-native-tree-multi-select#34]
Hey! 
Thanks for this incredible library! 

Is there an approach for getting the count of checked subNodes under a node? 

For example 

```
└── Cars (2 out of 3)/
    ├── [x] Hyundai
    ├── [x] Benz
    └── [ ] Tesla
```

**Comment by JairajJangle** [comment]
Hi @OmkarK45 👋! Thank you so much for your kind words! 😊 It’s great to hear that you find the module to be flexible and useful.

To help demonstrate how you can display the ratio of checked children to total children next to the node's name, I've prepared a small example for you: https://snack.expo.dev/@futurejj/ludicrous-red-popcorn. This example incorporates the `extraData` parameter in `treeFlashListProps` to ensure that all items in the FlashList are updated with the latest `checkedIds`. Please note, there might be more optimized ways to handle this.

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExYTU4c3ptM3hycDNicWprNnRmYjY1bHdhZjB4MHF2aWR2MjNkMm9pYyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/kOF7lv40JbnshOrdrn/giphy.gif)

For more details, take a look at the `getSuffix` function in _CustomNodeRowView.tsx_. Feel free to experiment with the customizations and see what works best for your project. Also, be sure to check out our [example app](https://github.com/JairajJangle/react-native-tree-multi-select/tree/main/example) for additional guidance and ideas.

I hope you find this helpful! Let me know how it works out for you, or if there’s anything else you’d like to discuss. Cheers! 🚀

**Comment by OmkarK45** [comment]
This is helpful, thanks a lot! Appreciate taking the time to create the expo snack too
