### ISSUE TITLE
[FEAT-REQ] key

### ISSUE THREAD

**Issue by ansarikhurshid786** [JairajJangle/react-native-tree-multi-select#65]
It is really useful and most update. 

I have very small enhancement request. If you accept name and children from props. It could be easy for us to pass any kind of data in our own structure.

it will reduce conversion to name and children.

**Comment by JairajJangle** [comment]
Hey there! 👋

Thank you for your kind words! 😊

I appreciate your enhancement request. However, I'm not entirely sure I understand the specific changes you're suggesting. Could you please provide an example of what you mean by accepting name and children from props and how it would help with passing any kind of data in your own structure? Additionally, an example of the data structure you are requesting would be very helpful.

The current structure of the tree data:
```typescript
export interface TreeNode {
    id: string;
    name: string;
    children?: TreeNode[];
    [key: string]: any;
}
```
 is already designed to accurately represent the Tree View structure, so understanding your perspective would be very helpful.

Thanks again for your feedback and looking forward to your example! 🙏
