### ISSUE TITLE
[FEAT-REQ] Being able to toggle parent without toggling children

### ISSUE THREAD

**Issue by Astremy** [JairajJangle/react-native-tree-multi-select#81]
Hello! I would like to use this lib, but there is a kind of problem..

I wonder if there is a way to only receive the checked/unchecked node and not every single checked one when we check a node? I mean, we can already do it with code but it's not super practical.

Also, it would come very handy (and that's my major issue) if we could "disable" the "toggleNodeAndChildren" function and other ones related (https://github.com/JairajJangle/react-native-tree-multi-select/blob/2657af5ce108e27cbfeac1a962bf16aee16bc164/src/helpers/toggleCheckbox.helper.ts#L10), in order to be able to select something without having it selecting all it's children or toggling the parent. I would like to be able to check the parent without having the children getting checked.

Another lib is already providing a way to do it (https://github.com/SimformSolutionsPvtLtd/react-native-tree-selection) with the "autoSelectParents" and "autoSelectChildren" parameters and I wonder if it would be possible to do something similar? Or give any way to disable it since it's really annoying to me ^^'

**Comment by JairajJangle** [comment]
Hey there! 👋

Thank you for showing interest in the library! 😊

Regarding your first point about receiving only the checked/unchecked node in the callback, that’s a great suggestion, and I believe it could be helpful for others as well. Would you mind creating a separate GitHub issue for this so we can track it more easily?

As for the second point, being able to disable the toggleNodeAndChildren functionality and handle parent/child selection independently does sound like a sensible feature to have. I’ll definitely look into implementing something similar to the parameters you mentioned (autoSelectParents and autoSelectChildren), or at least provide a way to disable the current behavior.

Thanks again for your feedback! If you have any more questions or ideas, feel free to share them. 🙏

**Comment by JairajJangle** [comment]
Hey @Astremy! 👋

Just wanted to let you know that the feature you requested has been released in [v1.5.0-beta.1](https://github.com/JairajJangle/react-native-tree-multi-select/releases/tag/v1.5.0-beta.1). 🎉

Please feel free to give it a try and let me know if you encounter any further issues. I’ll be closing this issue for now, but don’t hesitate to reach out if anything comes up. 🙏

Thanks again for your feature request and valuable feedback!
